name: Build app

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: 17

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build app
        run: ./gradlew createReleaseDistributable

      - name: Upload app
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: build/compose/binaries/main-release/app/